apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {
      worker_connections  10240;
    }

    stream {
      map $ssl_preread_server_name $targetStub {
        ~^(?<appid>.*?)\.(?<namespace>.*?)\. $appid-dapr.$namespace;
      }

      resolver   kube-dns.kube-system.svc.cluster.local;

      server {
        set $domain cluster.local;

        listen                50002;
        proxy_pass            $targetStub.svc.$domain:50002;
        proxy_connect_timeout 5s;
        ssl_preread           on;
      }
    }
