apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {
      worker_connections  10240;
    }

    stream {
      map $ssl_preread_server_name $targetStub {
        ~^(?<appid>.*?)\.(?<namespace>.*?)\. $appid-dapr.$namespace;
      }

      resolver kube-dns.kube-system.svc.cluster.local;

      log_format custom '##### [$time_local] $remote_addr $ssl_preread_server_name $targetStub '
                 '$protocol $status $bytes_sent $bytes_received';
      
      access_log /dev/stdout custom buffer=1k flush=1s;

      server {
        set $domain cluster.local;

        listen                50002;
        proxy_pass            $targetStub.svc.$domain:50002;
        proxy_connect_timeout 5s;
        ssl_preread           on;
      }
    }
