apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
spec:
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "receiver"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - name: receiver
          image: ghcr.io/benc-uk/dapr-tester/receiver:dev
          resources:
            limits:
              memory: "50Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
