apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "sender"
        # Use custom config, see config.yaml
        dapr.io/config: "gateway-config"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - name: sender
          image: ghcr.io/benc-uk/dapr-gateway-hack/sender:latest
          resources:
            limits:
              memory: "50Mi"
              cpu: "200m"
          env:
            - name: REMOTE_APP_ID
              # extended app-id format to go across remote gateway and second cluster called aks2
              value: "receiver.default.aks2"
              #value: "receiver"
            - name: INTERVAL
              value: "5"
