apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
spec:
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "sender"
    spec:
      containers:
        - name: sender
          image: ghcr.io/benc-uk/dapr-tester/sender:dev
          resources:
            limits:
              memory: "50Mi"
              cpu: "500m"
          env:
            - name: REMOTE_APP_ID
              value: "receiver"
            - name: REMOTE_METHOD
              value: "echo"
            - name: INTERVAL
              value: "5"
